BDProjeto/WebApplication/Controllers/FuncionarioController.cs
using BDProjeto.Aplicacao;
using BDProjeto.DTO.ExemploBD;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class FuncionarioController : Controller
    {
        private UsuarioContextBS business;
        
        public FuncionarioController()
        {
            business = UsuarioContextConstrutor.UsuarioApEF();
        }

        [HttpGet]
        public ActionResult Index()
        {
            //Linhas comentadas usam as chamdas do ADO para trabalhar com o banco de dados
            //var business = UsuarioContextConstrutor.UsuarioApADO();
            var listUsuarios = business.ListarTodos();

            return View(listUsuarios);
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Usuarios user)
        {
            if (ModelState.IsValid)
            {
                //var contexto = UsuarioContextConstrutor.UsuarioApADO();
                //contexto.Salvar(user);
                business.Salvar(user);
                return RedirectToAction("Index");
            }
            else
                return View(user);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            //var business = UsuarioContextConstrutor.UsuarioApADO();
            var user = business.GetUsuarioById(id.ToString());

            if (user == null)
                return HttpNotFound();
            else
                return View(user);
        }

        [HttpPost]
        public ActionResult Editar(Usuarios user)
        {
            if (ModelState.IsValid)
            {
                //var business = UsuarioContextConstrutor.UsuarioApADO();
                business.Salvar(user);
                return RedirectToAction("Index");
            }
            else
                return View(user);
        }

        [HttpGet]
        public ActionResult Detalhes(int id)
        {
            //var business = UsuarioContextConstrutor.UsuarioApADO();
            var user = business.GetUsuarioById(id.ToString());

            if (user == null)
                return HttpNotFound();
            else
                return View(user);
        }

        [HttpGet]
        public ActionResult Excluir(int id)
        {
            //var business = UsuarioContextConstrutor.UsuarioApADO();
            var user = business.GetUsuarioById(id.ToString());

            if (user == null)
                return HttpNotFound();
            else
                return View(user);
        }

        [HttpPost, ActionName("Excluir")]
        public ActionResult ExcluirConfirmado(int id)
        {
            //var business = UsuarioContextConstrutor.UsuarioApADO();
            var user = business.GetUsuarioById(id.ToString());
            business.ExcluirDados(user);
            return RedirectToAction("Index");
        }

    }
}

BDProjeto/WebApplication/Controllers/HomeController.cs
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


    }
}

BDProjeto/WebApplication/Views/Funcionario/Cadastrar.cshtml
@model BDProjeto.DTO.ExemploBD.Usuarios

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cadastro de funcionário</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.NOME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CARGO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CARGO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CARGO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BDProjeto/WebApplication/Views/Funcionario/Detalhes.cshtml
@model BDProjeto.DTO.ExemploBD.Usuarios

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NOME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOME)
        </dd>

        <dt>
            Cargo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CARGO)
        </dd>

        <dt>
            Data de admissão
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATAINSERCAO)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new {  id = Model.USUARIO_ID}) |
    @Html.ActionLink("Voltar", "Index")
</p>

BDProjeto/WebApplication/Views/Funcionario/Editar.cshtml
@model BDProjeto.DTO.ExemploBD.Usuarios

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.USUARIO_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.NOME, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOME, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOME, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CARGO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CARGO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CARGO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BDProjeto/WebApplication/Views/Funcionario/Excluir.cshtml
@model BDProjeto.DTO.ExemploBD.Usuarios

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<h3>Você deseja realmente excluir este registro?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        @Html.HiddenFor(model => model.USUARIO_ID)
        <dt>
            @Html.DisplayNameFor(model => model.NOME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NOME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CARGO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CARGO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATAINSERCAO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATAINSERCAO)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Cancelar", "Index")
        </div>
    }
</div>

BDProjeto/WebApplication/Views/Funcionario/Index.cshtml
@model IEnumerable<BDProjeto.DTO.ExemploBD.Usuarios>

@{
    ViewBag.Title = "Funcionários";
}

<h2>Funcionários</h2>

<p>
    @Html.ActionLink("Cadastrar funcionário", "Cadastrar")
</p>
<table class="table">
    <tr>
        <!-- <th>
            @Html.DisplayNameFor(model => model.USUARIO_ID)
        </th> -->
        <th>
            @Html.DisplayNameFor(model => model.NOME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CARGO)
        </th>
        <th>
            Data de admissão
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <!-- <td>
                        @Html.DisplayFor(modelItem => item.USUARIO_ID)
             </td> -->
            
            <td>
                @Html.DisplayFor(modelItem => item.NOME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CARGO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DATAINSERCAO)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.USUARIO_ID }) |
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.USUARIO_ID }) |
                @Html.ActionLink("Excluir", "Excluir", new { id = item.USUARIO_ID })
            </td>
        </tr>
    }

</table>

BDProjeto/WebApplication/Views/Home/Index.cshtml
@model IEnumerable<BDProjeto.DTO.ExemploBD.Usuarios>
@{
    ViewBag.Title = "Lista de usuários";
}

<h2>Página Inicial</h2>

BDProjeto/WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Funcionários", "Index", "Funcionario")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.ActionLink("Início", "Index", "Home")
        @Html.ActionLink("Cadastro de Funcionário", "Index", "Funcionario")

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>